import EventEmitter from 'events';

const CUSTOM_EVENTS = {
  IOS_LOCAL_NOTIFICATION: 'IOS_LOCAL_NOTIFICATION',
  IOS_SHOW_TOOL_BAR: 'IOS_SHOW_TOOL_BAR',

  CHAT_TOOL_BAR_SHOW_SEARCH: 'CHAT_TOOL_BAR_SHOW_SEARCH',
  CHAT_TOOL_BAR_CLOSE_SEARCH: 'CHAT_TOOL_BAR_CLOSE_SEARCH',

  CHAT_MODAL_FORWARD_SEARCH_QUERY: 'CHAT_MODAL_FORWARD_SEARCH_QUERY',

  IOS_DIALOGS_TOOL_BAR_BUTTON_PRESSED: 'IOS_DIALOGS_TOOL_BAR_BUTTON_PRESSED',

  // DIALOGS_TOOL_BAR_SHOW_SEARCH: 'DIALOGS_TOOL_BAR_SHOW_SEARCH',
  // DIALOGS_TOOL_BAR_CLOSE_SEARCH: 'DIALOGS_TOOL_BAR_CLOSE_SEARCH',
  CONTACTS_TOOL_BAR_SHOW_SEARCH: 'CONTACTS_TOOL_BAR_SHOW_SEARCH',
  CONTACTS_TOOL_BAR_CLOSE_SEARCH: 'CONTACTS_TOOL_BAR_CLOSE_SEARCH',
  CONTACTS_SEARCH_QUERY: 'CONTACTS_SEARCH_QUERY',

  SHARED_CONTACTS_TOOL_BAR_SHOW_SEARCH: 'SHARED_CONTACTS_TOOL_BAR_SHOW_SEARCH',
  SHARED_CONTACTS_TOOL_BAR_CLOSE_SEARCH:
    'SHARED_CONTACTS_TOOL_BAR_CLOSE_SEARCH',
  SHARED_CONTACTS_SEARCH_QUERY: 'SHARED_CONTACTS_SEARCH_QUERY',

  CHAT_HIDE_TITLE: 'CHAT_HIDE_TITLE',
  CHAT_SHOW_TITLE: 'CHAT_SHOW_TITLE',

  MUTE_DIALOG: 'MUTE_DIALOG',
  UNMUTE_DIALOG: 'UNMUTE_DIALOG',

  GET_USERS_FROM_APP: 'GET_USERS_FROM_APP',

  THEME_CHANGED: 'THEME_CHANGED',
  CALL_USER_HANG_UP: 'CALL_USER_HANG_UP',

  CURRENT_USER_REMOVED_FROM_DIALOG: 'CURRENT_USER_REMOVED_FROM_DIALOG',
  CURRENT_USER_ADMIN_ROLE_CHANGED: 'CURRENT_USER_ADMIN_ROLE_CHANGED',

  CALLS_HISTORY_SEARCH_QUERY: 'CALLS_HISTORY_SEARCH_QUERY',

  STORAGE_USAGE_SEARCH_QUERY: 'STORAGE_USAGE_SEARCH_QUERY',

  CURRENT_USER_LEAVE_GROUP: 'CURRENT_USER_LEAVE_GROUP',

  LOGOUT: 'LOGOUT',

  SHARE_INTENT_FROM_KEYBOARD: 'SHARE_INTENT_FROM_KEYBOARD',

  NAVIGATION_BUTTON_PRESSED_DIALOGS: 'NAVIGATION_BUTTON_PRESSED_DIALOGS',

  NAVIGATION_BUTTON_PRESSED_CHAT: 'NAVIGATION_BUTTON_PRESSED_CHAT',

  NAVIGATION_BUTTON_PRESSED_CALLS: 'NAVIGATION_BUTTON_PRESSED_CALLS',

  CHANGE_NAVIGATION_BUTTONS_ACTIONS_DIALOGS:
    'CHANGE_NAVIGATION_BUTTONS_ACTIONS_DIALOGS',

  CHANGE_NAVIGATION_BUTTONS_ACTIONS_CHAT:
    'CHANGE_NAVIGATION_BUTTONS_ACTIONS_CHAT',

  CHANGE_NAVIGATION_BUTTONS_ACTIONS_CALLS:
    'CHANGE_NAVIGATION_BUTTONS_ACTIONS_CALLS',

  RESET_CHATS_SEARCH: 'RESET_CHATS_SEARCH',

  UPDATE_HEADER_SUBTITLE: 'UPDATE_HEADER_SUBTITLE',

  ACCEPT_CALL: 'ACCEPT_CALL',

  BACK_JOIN_CHAT: 'BACK_JOIN_CHAT',

  BACK_MEETING: 'BACK_MEETING',

  BACK_SCHEDULE_MEETING: 'BACK_SCHEDULE_MEETING',

  PLAY_MESSAGE_SOUND: 'PLAY_MESSAGE_SOUND',

  REMOVE_SELECTED_CALL_PARTICIPANT: 'REMOVE_SELECTED_CALL_PARTICIPANT',
};

const customEventEmitter = new EventEmitter();

export {CUSTOM_EVENTS};

export default customEventEmitter;
